---
galaxy_info:
  author: Harsha Bhargav
  description: An Ansible role to install Amazon AWS Command Line Interface.
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags:
    - aws
    - amazon
    - cli
dependencies: []
allow_duplicates: yes
